version: '3.4'

services:
  client:
    container_name: jadeocr_client
    image: client
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      VUE_APP_API_BASEURL: ${VUE_APP_API_BASEURL}
    ports:
      - 8085:80
