version: '3.4'

services:
  server:
    extends:
      file: ./server/docker-compose.yml
      service: server
    runtime: nvidia
  client:
    extends:
      file: ./client/docker-compose.yml
      service: client
