version: '3.4'

services:
  server:
    container_name: jadeocr_server
    image: server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGOOSEURL: ${MONGOOSEURL}
    ports:
      - 3000:3000
